### PR TITLE
Fix sandbox

### PR DESCRIPTION
**Pull request by robkinyon**
All tests now pass after this patch on master. This reverts the payment_method_nonce patch and fixes the bits that still didn't work.

ZipRecruiter has requested you do *NOT* release until the payment_method_nonce/take_2 branch is merged. That's the branch where I'm going to reapply the payment_method_nonce patch and make sure the tests pass.

If possible, could you cut a release *before* merging this so that the new documentation can get out there?

### CODE REVIEW

**Comment by singingfish** [comment]
Yes, I can cut a docco only release over the weekend.

**Comment by singingfish** [comment]
v 0.92 released to the cpan, with docco changes but without the nonce changes.

**Comment by robkinyon** [comment]
This branch is ready to merge whenever. Once it's merged, then I'll rebase the payment_method_nonce/take_2 onto master, finish it, and we can merge that, then we'll have a clean master with all sandbox tests working properly. At that point, we can look at merging cleanup_util and start forging ahead.

**Comment by singingfish** [comment]
merged, ta

**Comment by robkinyon** [comment]
You closed this without merging it.

**Pull request closed without merging**
